config/routes.rb
NTUMB::Application.routes.draw do

  get "sub_pages/show"

  resources :sub_pages, :only => [:show]
  resources :teachers, :only => [:index, :show, :edit, :update]
  resources :news_reports, :only => [:index, :show]
  resources :documents, :only => [:index, :show]
  resources :announcements, :only => [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  filter :department, :exclude => %r(^/admin/)
  filter :locale, :exclude => %r(^/admin/)

  match "/*path" => 'pages#view'#, :as => :page
  match "/" => "pages#home"

end

app/views/pages/home/_carousel.html.erb
<div id="carousel" class="carousel slide">
  <div class="carousel-inner">
    <% @carousels.each_with_index do |c,i| %>
      <div class="item <%= "active" if i == 0 %>">
        <%= image_tag c.picture.url(:medium) %>
        <div class="carousel-caption">
          <% unless c.link_url.to_s.empty? %>
            <a href="<%= c.link_url %>">
              <h4><%= c.title %></h4>
              <p><%= c.caption %></p>
            </a>
          <% else %>
            <h4><%= c.title %></h4>
            <p><%= c.caption %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div><!-- end of carousel-inner -->
  <a class="carousel-control left" href="#carousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#carousel" data-slide="next">&rsaquo;</a>
</div><!-- end of carousel -->

app/views/pages/home/_stickers.html.erb
<div class="row margin40" id="stickers">
  <% @news.each_with_index do |news,i| %>
    <div class="span4">
      <div class="sticker well sticker<%=news.preview_color%>">
        <h4 class="<%= "en" if I18n.locale == :en %>"><%= news.title %></h4>
        <% unless news.text_up %>
          <%= image_tag(news.preview.url(:thumb)) %>
        <% end %>
        <div>
          <p class="<%= "en" if I18n.locale == :en %>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= news.preview_text %><%= link_to "...more", news_report_path(news) %></p>
        </div>
        <% if news.text_up %>
          <%= image_tag(news.preview.url(:thumb)) %>
        <% end %>
      </div>
    </div>
  <% end %>
</div><!-- end of row -->
<div class="row" id="stickers">
  <% @news2.each_with_index do |news,i| %>
    <div class="span4">
      <div class="sticker well sticker<%=news.preview_color%>">
        <h4 class="<%= "en" if I18n.locale == :en %>"><%= news.title %></h4>
        <% unless news.text_up %>
          <%= image_tag(news.preview.url(:thumb)) %>
        <% end %>
        <div>
          <p class="<%= "en" if I18n.locale == :en %>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= news.preview_text %><%= link_to "...more", news_report_path(news) %></p>
        </div>
        <% if news.text_up %>
          <%= image_tag(news.preview.url(:thumb)) %>
        <% end %>
      </div>
    </div>
  <% end %>
</div><!-- end of row -->

app/views/pages/home/_tab_contents.html.erb
<% items.each do |a| %>
  <tr>
    <td class="announce_date">
      <a href="<%= announcement_path(a) %>">
        <span><%= a.announce_date.to_s %></span>
      </a>
    </td>
    <td>
      <a class="<%= "sticky" if a.sticky %>" href="<%= announcement_path(a) %>">
        <span>
          <%= a.name %>
        </span>
      </a>
    </td>
  </tr>
<% end %>

app/views/pages/home/_tabs.html.erb
<ul class="nav nav-tabs" id="home-tabs">
    <% first_appear = true %>
    <% appear_flag = -1 %>
    <% @tabs.each_with_index do |tab,i| %>
      <% if tab.visible %>
        <li class="<%= "active" if first_appear %>">
          <a data-toggle="tab" href="#home-tab-<%= i %>">
            <%= tab.first_name %><br class="visible-980-1200"/><%= tab.last_name %>
          </a>
        </li>
        <% appear_flag = i if first_appear == true%>
        <% first_appear = false %>
      <% end %>
    <% end %>
</ul>
<div class="tab-content well" id="home-tabs-content">
  <% @tabs.each_with_index do |tab,i| %>
    <% if tab.visible %>
      <% unless tab.is_youtube? %>
        <div id="home-tab-<%= i %>" class="tab-pane unstyled <%= "active" if appear_flag == i %>">
          <table border="0">
            <%= render partial: "pages/home/tab_contents", locals: { items: @tab_contents[i] } %>
          </table>
        </div>
      <% else %>
        <ul class="youtube-channel tab-pane unstyled <%= "active" if appear_flag == i %>" 
            id="home-tab-<%= i %>">
          <%= render partial: "pages/home/youtube_tab", locals: { videos: @tab_contents[i] } %>
        </ul>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/pages/home/_youtube_tab.html.erb
<% if @youtube_timeout %>
  <div class="youtube-error">Can't connect to google</div>
<% else %>
  <% videos.each do |v| %>
    <li>
      <a href="<%= html_escape v['video_url'] %>">
        <span class="video-thumb-wrapper">
          <span class="video-thumb">
            <span class="video-thumb-inner">
              <%= image_tag(v['thumb_url']) %>
            </span>
            <span class="duration"><%= v['duration'] %></span>
          </span>
        </span>
        <div class="video-info invisible-768-979">
          <span class="video-title"><%= v['title'] %></span><br />
          <span class="video-stats">
            <%= I18n.t "front_end.announce_date" %>: <%= "#{v['published_at']}" %>
          </span>
        </div>
      </a>
    </li>
  <% end %>
<% end %>