config/routes.rb
NTUMB::Application.routes.draw do

  get "sub_pages/show"

  resources :sub_pages, :only => [:show]
  resources :teachers, :only => [:index, :show, :edit, :update]
  resources :news_reports, :only => [:index, :show]
  resources :documents, :only => [:index, :show]
  resources :announcements, :only => [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  filter :department, :exclude => %r(^/admin/)
  filter :locale, :exclude => %r(^/admin/)

  match "/*path" => 'pages#view'#, :as => :page
  match "/" => "pages#home"

end

app/views/shared/_attachments.html.erb
<ul class="unstyled attachments">
  <% documents.each_with_index do |document,i| %>
    <li>
      <span><%= I18n.t "front_end.attachments" %><%= i + 1 %>：</span>
      <%= link_to document.document_file_file_name, document.document_file.url %>
    </li>
  <% end %>
</ul>

app/views/shared/_department_links.html.erb
<div id="<%= "emba-" if emba %>department-links-wrapper">
  <div class="container">
    <ol id="<%= "emba-" if emba %>department-links" class="nav nav-pills">
      <% @department_names.each_with_index do |dname,i|  %>
        <% if i == 0 %>
          <li><%= link_to I18n.t("front_end.Management"), @management_link %></li>
        <% else %>
          <% unless dname == "GMBA" %>
            <li><%= link_to I18n.t("front_end.#{dname}"), @all_departments_links.at(i) %></li>
          <% else %>
            <li><%= link_to "GMBA", "/en/GMBA" %></li>
          <% end %>
        <% end %>
      <% end %>
    </ol>
  </div>
</div><!-- end of department-links-wrapper -->

app/views/shared/_footer.html.erb
<div id="footer">
  <%= render partial: "shared/department_links", locals: { emba: false }%>
  <div id="info-wrapper">
    <div id="info" class="container">
      <span id="copyright">
        <small> &copy; National Taiwan University All Rights Reserved</small>
      </span>
      <address>
        <span><small><%= @address %></small></span>
        <br/>
        <span>
          <small><%= I18n.t("front_end.phone") %>：<%= @phone_one %>; <%= @phone_two %> 
          <%= I18n.t("front_end.tax") %>：<%= @tax_num %></small>
        </span>
      </address>
    </div><!-- end of info -->
  </div>
</div><!-- end of footer -->

app/views/shared/_footer0410.html.erb
<div id="footer">
  <%= render partial: "shared/department_links", locals: { emba: false }%>
  <div id="info-wrapper">
    <div id="info" class="container">
      <span id="copyright">
        <small> &copy; National Taiwan University All Rights Reserved</small>
      </span>
      <address>
        <span><small><%= @address %></small></span>
        <br/>
        <span>
          <small><%= I18n.t("front_end.phone") %>：<%= @phone_one %>; <%= @phone_two %> 
          <%= I18n.t("front_end.tax") %>：<%= @tax_num %></small>
        </span>
      </address>
    </div><!-- end of info -->
  </div>
</div><!-- end of footer -->

app/views/shared/_footer04100.html.erb
<div id="footer">
  <%= render partial: "shared/department_links", locals: { emba: true }%>
  <div id="info-wrapper" >
    <div id="emba-info" class="container">
   <ul style="display:inline-block;margin-top: 30px 30px 0 6pxpx">
		  <%= image_tag("QTEMLogo.jpg")%></ul>
		  <ul style="display:inline-block;margin-top: 30px ">
		  <%= image_tag("GMACLogo.jpg") %></ul>
		  <ul style="display:inline-block;margin-top: 30px ;text-align: right;float: right;">
          <span>
            <small> &copy; National Taiwan University All Rights Reserved</small>
          </span>
          <address>
            <span><small><%= @address %></small></span>
            <br/>
            <span>
              <small><%= I18n.t("front_end.phone") %>：<%= @phone_one %>; <%= @phone_two %> 
              <%= I18n.t("front_end.tax") %>：<%= @tax_num %></small>
            </span>
          </address></ul>
	
	  
	 
      </div>
    </div><!-- end of info -->
  </div>
</div><!-- end of footer -->
  

app/views/shared/_header.html.erb
<div id="header-wrapper">
  <div class="container" id="header">
    <div class="row">
      <div class="span7">
          <a href="<%= @header_link %>">
            <%= image_tag("logo.png", class: "header-logo") %>
            <h1 class="kai <%= "en" if I18n.locale == :en %>">
              <span class="invisible-768-979">
                <%= @header_school_prefix unless I18n.locale == :en%>
              </span>
              <%= @header_text %>
            </h1>
            <span class="<%= "en" if I18n.locale == :en %>">
              National Taiwan University <br class="visible-768-979"/>  College of Management
            </span>
         </a>
      </div>
      <div class="span5">
        <div class="header-info">
          <form class="form-search" action="http://www.google.com/search">
            <input type="text" placeholder="search" name="q" class="input-medium search-query">
            <input type="hidden" name="sitesearch" value="<%= request.host %>" />
            <button type="submit"><i class="icon-search"></i></button>
          </form>
          <% if I18n.locale == :en %>
            <% unless @current_department_name == "GMBA" %>
              <%= 
                link_to "中文", 
                  ("/" + (@current_department_name == "management" ? "" : "#{@current_department_name}")) 
              %>
            <% else %>
              <%= link_to "中文", '/' %>
            <% end %>
          <% else %>
            <%= 
              link_to "English", 
              ("/en" + (@current_department_name == "management" ? "" : "/#{@current_department_name}"))
            %>
          <% end %>
          <%= link_to I18n.t("front_end.contact"), "mailto:#{@contact_info}" %>
          <%= link_to I18n.t("front_end.sitemap"), @management_link %>
          <%= link_to I18n.t("front_end.ntu_site"), "http://www.ntu.edu.tw" %>
        </div>
        <%= image_tag("aacsb.png",width: "180", class: "aacsb") %>
      </div>
    </div><!-- row -->
  </div><!-- header -->
</div><!-- header-wrapper -->

app/views/shared/_header1126.html.erb
<div id="header-wrapper">
  <div class="container" id="header">
    <div class="row">
      <div class="span6">
          <a href="<%= @header_link %>">
            <%= image_tag("logo.png", size: "60x60") %>
            <h1 class="kai"><%= @header_text %></h1>
            <span>National Taiwan University College of Management</span>
         </a>
      </div>
      <div class="span6">
        <div class="header-info">
          <form class="form-search">
            <input type="text" placeholder="search" class="input-medium search-query">
            <button type="submit"><i class="icon-search"></i></button>
          </form>
          <% if I18n.locale == :en %>
            <%= link_to "中文", "/" %>
          <% else %>
            <%= link_to "English", "/en" %>
          <% end %>
          <%= link_to I18n.t("front_end.contact"), "/contact" %>
          <%= link_to I18n.t("front_end.sitemap"), "/sitemap" %>
          <%= link_to I18n.t("front_end.ntu_site"), "http://www.ntu.edu.tw" %>
        </div>
        <%= image_tag("aacsb.png",width: "180", class: "aacsb") %>
      </div>
    </div><!-- row -->
  </div><!-- header -->
</div><!-- header-wrapper -->

app/views/shared/_menu.html.erb
<div id="<%= "emba-" if emba %>menu-wrapper">
  <div class="container">
    <ol id="<%= "emba-" if emba %>main-menu" class="menu nav nav-pills">
      <% @menu.each do |menu_name,path_and_children| %>
        <% has_child = !path_and_children[:children].empty? %>
        <li <%= has_child ? "class='dropdown'" : "" %>>
          <% if has_child %>
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
              <%= menu_name.to_s %>
              <span class="caret"></span>
            </a>
            <%= render :partial => "shared/menu_branch", :object => path_and_children[:children]%>
          <% else %>
            <%= link_to menu_name.to_s, path_and_children[:path] %>
          <% end %>
        </li>
      <% end %>
    </ol>
  </div>
</div><!-- end of main-wrapper -->

app/views/shared/_menu_branch.html.erb
<ol class="dropdown-menu">
  <% menu_branch.each do |menu_name,path_and_children| %>
    <% has_child = !(path_and_children[:children].empty?) %>
    <% unless has_child %>
    <li>
      <%= link_to menu_name.to_s, path_and_children[:path] %>
    </li>
    <% else %>
      <li class="dropdown-submenu">
        <%= link_to menu_name.to_s, "#" %>
        <%= render :partial => "shared/menu_branch_lv3", :object => path_and_children[:children]%>
      </li>
    <% end %>
  <% end %>
</ol>

app/views/shared/_menu_branch_lv3.html.erb
<ol class="dropdown-menu">
  <% menu_branch_lv3.each do |menu_name,path_and_children| %>
    <li>
      <%= link_to menu_name.to_s, path_and_children[:path] %>
    </li>
  <% end %>
</ol>

app/views/shared/_pagenav.html.erb
<ul class="nav nav-list page-nav">
  <% @nav_list.each_with_index do |n,i| %>
    <% 
      has_sub = false 
      if n[1] == "#" 
        has_sub = true 
      end
    %>
    <li class="<%= "nav-parent " if i==0 %><%= "nav-lv#{n[2]} " %>">
      <a href="<%= n[1] %>">
        <%= n[0] %>
        <% if has_sub %>
          <span class="caret middle"></span>
        <% end %>
      </a>
    </li>
  <% end %>
</ul>

app/views/shared/_sub_pages.html.erb
<ul class="unstyled sub-pages">
  <% @page.sub_page_sections.each_with_index do |section,i| %>
    <h4><%= section.section_title %></h3>
    <% section.sub_pages.each_with_index do |sub_page,i| %>
      <li>
        <%= link_to sub_page.title, sub_page_path(sub_page) %>
      </li>
    <% end %>
  <% end %>
</ul>