config/routes.rb
NTUMB::Application.routes.draw do

  get "sub_pages/show"

  resources :sub_pages, :only => [:show]
  resources :teachers, :only => [:index, :show, :edit, :update]
  resources :news_reports, :only => [:index, :show]
  resources :documents, :only => [:index, :show]
  resources :announcements, :only => [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  filter :department, :exclude => %r(^/admin/)
  filter :locale, :exclude => %r(^/admin/)

  match "/*path" => 'pages#view'#, :as => :page
  match "/" => "pages#home"

end

app/models/document.rb
class Document < ActiveRecord::Base
  acts_as_paranoid
  attr_accessible :document_category_id, :document_file, :department_id, :discription, 
                  :announcement_id, :news_report_id, :page_id
  belongs_to :document_category
  belongs_to :department
  belongs_to :announcement
  belongs_to :news_report
  belongs_to :page
  has_attached_file :document_file

  validates_attachment :document_file, presence: true

  attr_accessible :translations_attributes
  translates :discription, :fallbacks_for_empty_translations => true
  class Translation
    attr_accessible :locale, :discription
  end
  accepts_nested_attributes_for :translations

  scope :recent, proc{|n = 3| order("created_at DESC").limit(n)}

  def publish_date
    self.updated_at.to_date
  end

end
::MyUtils.add_department_scopes(Document)
#(Department::DEPARTMENTS + Department::INTERNATIONAL_AFFAIRS).each do |department_name|
  #Document.instance_eval %Q{
    #def #{department_name}
      #Department.find_by_name("#{department_name}").documents
    #end
    #def #{department_name.downcase}
      #Department.find_by_name("#{department_name}").documents
    #end
    #def #{department_name.upcase}
      #Department.find_by_name("#{department_name}").documents
    #end
  #}
#end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_filter :build_nav_list

  def index
    @documents = Document.send(@current_department_name)
  end

  def show
    @document = Document.find(params[:id])
  end

private

  def build_nav_list
    @nav_list = department_page_variable.nav_list_for("documents")
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/index.html.erb
<div class="row">
  <div class="span3">
    <%= render partial: "shared/pagenav" %>
  </div>
  <div class="span9">
    <div class="tabbable">
      <ul class="nav nav-tabs">
        <% DocumentCategory.all.each_with_index do |c,i| %>
          <li <%= "class='active'" if i == 0 %>>
            <a href="#ann_<%= c.name %>" data-toggle="tab"><%= c.name %></a>
          </li>
        <% end %>
      </ul>
      <div class="tab-content">
        <% DocumentCategory.all.each_with_index do |c,i| %>
          <div class="tab-pane <%= 'active' if i == 0 %>" id="ann_<%= c.name %>">
            <% c.documents.each do |d| %>
              <a href="<%= document_path(d) %>">
                <h4><%= d.document_file_file_name %></h4>
              </a>
              <span><%= d.discription %></span>
              <span class="date-duration">
                <%= d.publish_date.strftime("%Y/%m/%d") %>
              </span>
            <% end %>
          </div>
        <% end %>
      </div><!-- tab-content -->
    </div><!-- tabbable -->
  </div>
</div>

app/views/documents/show.html.erb
<div class="row">
  <div class="span3">
    <%= render partial: "shared/pagenav" %>
  </div>
  <div class="span9">
    <h1><%= @document.document_file_file_name %></h1>
    <p><%= @document.discription %></p>
    <%= link_to(I18n.t("front_end.download_link"),@document.document_file.to_s, class: "download") %>
  </div>
</div>