config/routes.rb
NTUMB::Application.routes.draw do

  get "sub_pages/show"

  resources :sub_pages, :only => [:show]
  resources :teachers, :only => [:index, :show, :edit, :update]
  resources :news_reports, :only => [:index, :show]
  resources :documents, :only => [:index, :show]
  resources :announcements, :only => [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  filter :department, :exclude => %r(^/admin/)
  filter :locale, :exclude => %r(^/admin/)

  match "/*path" => 'pages#view'#, :as => :page
  match "/" => "pages#home"

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  acts_as_paranoid
  attr_accessible :cellphone, :department_id, :email, :homepage, :name, :phone,
                  :tax_number, :avatar, :teacher_title_id, :room, :joint_with, :front_end_order,
                  :picked_by_emba, :picked_by_gmba, :use_newweb_data, :ntu_seq
  attr_accessible :educational_backgrounds_attributes
  attr_accessible :courses_attributes
  attr_accessible :research_areas_attributes
  has_attached_file :avatar
  has_many :research_areas, :through => :researchings
  has_many :researchings
  has_many :courses
  has_many :educational_backgrounds
  has_many :newweb_teacher_publications

  scope :picked_by_emba, lambda { where(picked_by_emba: true) }
  scope :picked_by_gmba, lambda { where(picked_by_gmba: true) }

  belongs_to :admin_user
  belongs_to :department
  belongs_to :teacher_title

  attr_accessible :translations_attributes
  translates :honor, :history, :name, :room, :fallbacks_for_empty_translations => true
  class Translation
    attr_accessible :locale, :name, :room, :honor, :history
  end
  accepts_nested_attributes_for :translations

  accepts_nested_attributes_for :courses,# :reject_if => proc { |c| c[:name].blank?},
                                :allow_destroy => true
  accepts_nested_attributes_for :research_areas,# :reject_if => proc { |r| r[:name].blank?},
                                :allow_destroy => true
  accepts_nested_attributes_for :educational_backgrounds,# :reject_if => proc { |e| e[:name].blank? },
                                :allow_destroy => true

end
::MyUtils.add_department_scopes(Teacher)

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  before_filter :build_nav_list

  def index
    #@teachers = Teacher.page(params[:page])
    if @current_department_name == "management"
      @teachers = Teacher.order("front_end_order DESC")
      @departments = Department::DEPARTMENTS.clone # + [Department::INTERNATIONAL_AFFAIRS])
      @departments.shift
    elsif @current_department_name.downcase == "emba" 
      @teachers = Teacher.picked_by_emba.order("front_end_order DESC") + \
                  Teacher.send(@current_department_name).order("front_end_order DESC")
      @departments = Department::DEPARTMENTS.clone # + [Department::INTERNATIONAL_AFFAIRS])
      @departments.shift
    elsif @current_department_name.downcase == "gmba"
      @teachers = Teacher.picked_by_gmba.order("front_end_order DESC") + \
                  Teacher.send(@current_department_name).order("front_end_order DESC")
      @departments = Department::DEPARTMENTS.clone # + [Department::INTERNATIONAL_AFFAIRS])
      @departments.shift
    else
      @teachers = Teacher.send(@current_department_name).order("front_end_order DESC")
      @departments = [@current_department.name]
    end
    @colors = @departments.map{|d| Department::DCOLORS[d]}
    @title_categories = TeacherTitle.order("teacher_order DESC") 
  end

  def show
    @teacher = Teacher.find(params[:id])
    @seqFound = false
    @color = Department::DCOLORS[@teacher.department.name]
    @use_newweb_data = false
    if @teacher.use_newweb_data
      @use_newweb_data = true
      fetch_newweb_data
    else
      parse_ntu_teacher_publication
    end
    @homepage = url_with_protocol(@teacher.homepage)
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
  end

private

  def fetch_newweb_data
    @paper = @teacher.newweb_teacher_publications.paper.sort_by{|p| p.year}.reverse.map do |paper_node|
                {
                  author: paper_node.author,
                  year: paper_node.year,
                  title: paper_node.title,
                  journal: paper_node.journal_or_conference_orpublisher,
                  remarks: paper_node.other,
                  cate: ""
                }
             end
    @conference_paper = @teacher.newweb_teacher_publications.conference.sort_by{|p| p.year}.reverse.map do |paper_node|
                          {
                            author: paper_node.author,
                            year: paper_node.year,
                            title: paper_node.title,
                            conference: paper_node.journal_or_conference_orpublisher,
                            date: "",
                            location: paper_node.other
                          }
                        end
    @books = @teacher.newweb_teacher_publications.book.sort_by{|p| p.year}.reverse.map do |paper_node|
            {
              author: paper_node.author,
              year: paper_node.year,
              title: paper_node.title,
              remarks: "",
              publisher: paper_node.journal_or_conference_orpublisher,
              book_title: paper_node.other
            }
            end
    @other_publications = @teacher.newweb_teacher_publications.other.sort_by{|p| p.year}.reverse.map do |paper_node|
        {
          author: paper_node.author,
          year: paper_node.year,
          title: paper_node.title,
          remarks: "",
          publisher: paper_node.journal_or_conference_orpublisher,
          book_title: paper_node.other
        }
    end
  end

  def parse_ntu_teacher_publication
    all_xml = Nokogiri::XML(open("http://versatile.management.ntu.edu.tw/publication/all.xml").read)
    teacher_node = all_xml.xpath("//TeacherName").detect do |node| 
                                node.text == @teacher.translation_for("zh-TW").name 
                              end
    unless teacher_node.nil?
      ntuseq = (teacher_node.parent>"NTUseq").text
      @seqFound = true
      paper_xml = Nokogiri::XML( \
        open("http://versatile.management.ntu.edu.tw/publication/journal/#{ntuseq}.xml"))
      @paper = paper_xml.xpath("//Paper").map do |paper_node|
                  {
                    author: (paper_node>"Authors").text,
                    year: (paper_node>"PublishYear").text,
                    title: (paper_node>"PaperTitle").text,
                    journal: (paper_node>"PublishOn").text,
                    remarks: (paper_node>"Remarks").text,
                    cate: ((paper_node>"subgroup")>"group").text
                  }
                end
      conference_xml = Nokogiri::XML( \
        open("http://versatile.management.ntu.edu.tw/publication/conference/#{ntuseq}.xml"))
      @conference_paper = conference_xml.xpath("//Paper").map do |cp_node|
                            {
                              author: (cp_node>"Authors").text,
                              year: (cp_node>"PublishYear").text,
                              title: (cp_node>"PaperTitle").text,
                              conference: (cp_node>"PublishOn").text,
                              date: Date::MONTHNAMES[(cp_node>"PublishMonth").text.to_i],
                              location: (cp_node>"Location").text
                            }
                          end
      books_xml = Nokogiri::XML( \
        open("http://ann.cc.ntu.edu.tw/Achv/xmlBook.asp?Seq=#{ntuseq}"))
      @books = books_xml.xpath("//Book").map do |book_node|
          {
            author: (book_node>"Authors").text,
            year: (book_node>"PublishYear").text,
            title: (book_node>"DocTitle").text,
            remarks: (book_node>"Remarks").text,
            publisher: (book_node>"Publisher").text,
            book_title: (book_node>"BookTitle").text
          }
      end
    end
  end

  def build_nav_list
    @nav_list = department_page_variable.nav_list_for("teachers")
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_teacher_title_bar.html.erb
<div class="list-title">
  <div class="left-title">
    <div class="list-padding">
      <span class="list-padding-inner">&nbsp;</span>
    </div>
    <div class="title-content">
      <span><%= title_name %></span>
    </div>
  </div>
  <div class="filler">&nbsp;</div>
</div>
<div class="float-buffer"></div>

app/views/teachers/edit.html.erb
<h1>Teachers#edit</h1>
<p>Find me in app/views/teachers/edit.html.erb</p>

app/views/teachers/index.html.erb
<div class="row">
  <div class="span3">
    <%= render partial: "shared/pagenav" %>
  </div>
  <div class="span9">
    <div id="expanding" class="accordion">
        <% @departments.each_with_index do |d,i| %>
          <div class="accordion-group">
            <div class="accordion-heading">
              <div class="department-stuffing stuffing stuffing-<%= @colors[i] %>">
                <span class="department-inner-stuffing inner-stuffing stuffing-<%= @colors[i] %>">&nbsp;</span>
              </div>
              <a data-parent="expanding" href="#ttc_<%= d %>"
                 class="accordion-toggle teacher-department" data-toggle="collapse">
                 <%= I18n.t "front_end.teacher.department.#{d}" %>
              </a>
            </div>
            <div class="accordion-body collapse
              <%= "in" if @current_department_name.downcase != "management"%>" id="ttc_<%= d %>">
              <div class="accordion-inner">
                <% @title_categories.each_with_index do |tc,j| %>
                  <span class="teacher_title">
                    <%= tc.title_name %>
                  </span>
                  <ul class="teachers border-<%= @colors[i] %> pixel-pattern-<%= @colors[i] %> ">
                    <% ts =  @teachers.select{|ts| ts.teacher_title == tc 
                                      }.select{|ts| ts.department == Department.find_by_name(d) } %>
                    <% unless ts.empty? %>
                      <% ts.each do |teacher| %>   
                        <li class="teacher-item">
                          <%= link_to teacher.name, teacher_path(teacher) %>
                        </li>
                      <% end %>
                    <% else %>
                      <li>
                        <%= I18n.t "front_end.teacher.none" %>
                      </li>
                    <% end %>
                  </ul>
                <% end %>
              </div> <!-- .accordion-inner -->
            </div> <!-- .accordion-body -->
          </div> <!-- .accordion-group -->
        <% end %>
    </div> <!-- #expanding -->
  </div> <!-- end of span 9 -->
</div> <!-- end of row -->

app/views/teachers/index_bk.html.erb
<div class="row">
  <div class="span3">
    <%= render partial: "shared/pagenav" %>
  </div>
  <div class="span9">
    <div id="expanding" class="accordion">
      <% @title_categories.each_with_index do |tc,i| %>
        <div class="accordion-group">
          <div class="accordion-heading">
            <a data-parent="expanding" href="#tt_<%= tc.translation_for(:en).title_name.gsub(/ /,'_') %>"
               class="accordion-toggle" data-toggle="collapse">
              <%= tc.title_name %>
            </a>
          </div>
          <div class="accordion-body collapse in" 
               id="tt_<%= tc.translation_for(:en).title_name.gsub(/ /,'_') %>">
            <div class="accordion-inner">
              <table border="0" class="fixed">
                <col width="170px" />
                <col width="170px" />
                <col width="170px" />
                <col width="170px" />
                <tr>
                  <td class="teacher-data-name"><%= I18n.t "front_end.teacher.name" %></td>
                  <td class="teacher-data-name">E-mail</td>
                  <td class="teacher-data-name"><%= I18n.t "front_end.teacher.room" %></td>
                  <td class="teacher-data-name"><%= I18n.t "front_end.teacher.homepage" %></td>
                </tr>
                <% tc.teachers.each do |teacher| %>
                  <% if @teachers.include?(teacher) %>
                    <tr>
                      <td class="teacher-data teacher-name">
                        <%= link_to teacher.name, teacher_path(teacher) %>
                      </td>
                      <td class="teacher-data">
                        <%= teacher.email %>
                      </td>
                      <td class="teacher-data teahcer-room">
                        <%= teacher.room %>
                      </td>
                      <td class="teacher-data">
                        <%= link_to teacher.homepage, teacher.homepage %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </table>
            </div>
          </div>
        </div><!-- accordion-group -->
      <% end %> <!-- each title_categories -->
    </div><!-- #expanding -->
  </div>
</div>

app/views/teachers/show.html.erb
<div class="row">
  <div class="span3">
    <%= render partial: "shared/pagenav" %>
  </div>
  <div class="span9">
    <div class="title-wrapper border-<%= @color %>">
      <div class="teacher-stuffing stuffing stuffing-<%= @color %>">
        <span class="teacher-inner-stuffing inner-stuffing stuffing-<%= @color %>">&nbsp;</span>
      </div>
      <span><%= @teacher.teacher_title.title_name %></span>
    </div>
    <div class="teacher-data-container">
      <div class="teacher-pic-wrapper">
        <img src="<%= @teacher.avatar.url %>" 
             alt="<%= @teacher.teacher_title.title_name + " " + @teacher.name %>" 
             class="teacher-avatar"/>
      </div>
      <div class="teacher-data">
        <table class="">
          <tr>
            <td><%= I18n.t "front_end.teacher.title" %></td>
            <td><%= @teacher.teacher_title.title_name %></td>
          </tr>
          <tr>
            <td><%= I18n.t "front_end.teacher.name" %></td>
            <td><%= @teacher.name %></td>
          </tr>
          <tr>
            <td><%= I18n.t "front_end.teacher.room" %></td>
            <td><%= @teacher.room %></td>
          </tr>
          <tr>
            <td><%= I18n.t "front_end.teacher.phone" %></td>
            <td><%= @teacher.phone %></td>
          </tr>
          <tr>
            <td><%= I18n.t "front_end.teacher.cellphone" %></td>
            <td><%= @teacher.cellphone %></td>
          </tr>
          <tr>
            <td><%= I18n.t "front_end.teacher.tax" %></td>
            <td><%= @teacher.tax_number %></td>
          </tr>
          <tr>
            <td><%= I18n.t "front_end.teacher.homepage" %></td>
            <td><%= link_to @homepage, @homepage %></td>
          </tr>
          <tr>
            <td><%= I18n.t "front_end.teacher.email" %></td>
            <td><%= mail_to @teacher.email, @teacher.email %></td>
          </tr>
          <tr>
            <td valign="center"><%= I18n.t "front_end.teacher.research_areas" %></td>
            <td>
              <% @teacher.research_areas.each do |ra| %>
                <li><%= ra.name %></li>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <div class="title-wrapper border-<%= @color %>">
      <div class="tab-stuffing stuffing stuffing-<%= @color %>">
        <span class="tab-inner-stuffing inner-stuffing stuffing-<%= @color %>">&nbsp;</span>
      </div>
      <ul class="info-tabs">
        <li class="active">
          <a href="#teacher-course" data-toggle="tab">
            <%= I18n.t "front_end.teacher.educational_backgrounds" %> & 
            <%= I18n.t "front_end.teacher.courses" %>
          </a>
        </li>
        <li>
          <a href="#teacher-history" data-toggle="tab">
            <%= I18n.t "front_end.teacher.honor" %> &
            <%= I18n.t "front_end.teacher.history" %>
          </a>
        </li>
        <li>
          <a href="#teacher-paper" data-toggle="tab">
            <%= I18n.t "front_end.teacher.publication.paper" %>
          </a>
        </li>
        <li>
          <a href="#teacher-conference" data-toggle="tab">
            <%= I18n.t "front_end.teacher.publication.conference" %>
          </a>
        </li>
        <li>
          <a href="#teacher-book" data-toggle="tab">
            <%= I18n.t "front_end.teacher.publication.book" %>
          </a>
        </li>
        <li>
          <a href="#teacher-other" data-toggle="tab">
            <%= I18n.t "front_end.teacher.publication.other" %>
          </a>
        </li>
      </ul>
    </div>
    <div class="tab-content">
      <div class="tab-pane active" id="teacher-course">
        <%= render partial: "teacher_title_bar",
                   locals: { title_name: I18n.t("front_end.teacher.educational_backgrounds") } %>
        <div class="items">
          <% unless @teacher.educational_backgrounds.empty? %>
            <ul>
              <% @teacher.educational_backgrounds.each do |eb| %>
                <li><%= eb.name %></li>
              <% end %>
            </ul>
          <% else %>
            <div><%= I18n.t "front_end.teacher.no_data" %></div>
          <% end %>
        </div>
        <%= render partial: "teacher_title_bar",
                   locals: { title_name: I18n.t("front_end.teacher.courses") } %>
        <div class="items">
          <% unless @teacher.courses.empty? %>
          <ul>
            <% @teacher.courses.each do |course| %>
              <li>
              <% if course.course_url.to_s.empty? %>
                <%= course.name %>
              <% else %>
                <%= link_to course.name, course.course_url %>
              <% end %>
              </li>
            <% end %>
          </ul>
          <% else %>
            <div><%= I18n.t "front_end.teacher.no_data" %></div>
          <% end %>
        </div>
      </div>
      <div class="tab-pane" id="teacher-history">
        <%= render partial: "teacher_title_bar",
                   locals: { title_name: I18n.t("front_end.teacher.honor") } %>
        <div class="items">
          <% unless @teacher.honor.to_s.empty? %>
            <ul>
              <%= raw sanitize(simple_format(@teacher.honor), :tags => %w(br p) ) %>
            </ul>
          <% else %>
            <div><%= I18n.t "front_end.teacher.no_data" %></div>
          <% end %>
        </div>
        <%= render partial: "teacher_title_bar",
                   locals: { title_name: I18n.t("front_end.teacher.history") } %>
        <div class="items">
          <% unless @teacher.history.to_s.empty? %>
            <ul>
              <%= raw sanitize(simple_format(@teacher.history), :tags => %w(br p) ) %>
            </ul>
          <% else %>
            <div><%= I18n.t "front_end.teacher.no_data" %></div>
          <% end %>
        </div>
      </div>
      <div class="tab-pane" id="teacher-paper">
        <%= render partial: "teacher_title_bar",
                   locals: { title_name: I18n.t("front_end.teacher.publication.paper") } %>
        <div class="items">
          <% if @paper.present? %>
            <ul class="publications" >
              <% @paper.each do |paper| %>
                <li>
                  <%="#{paper[:author]}" %>
                  <%=", #{paper[:year]}" unless paper[:year].to_s.empty? || paper[:year] == "N/A" || paper[:year] == "0"%>
                  <%=", #{paper[:title]}" unless paper[:title].to_s.empty? || paper[:title] == "N/A" || paper[:title] == "0"%>
                  <%=", #{paper[:journal]}" unless paper[:journal].to_s.empty? || \
                                                 paper[:journal] == "N/A" || paper[:journal] == "0"%>
	              <%=", Vol.#{paper[:volume]}" unless paper[:volume].to_s.empty? || \
							                       paper[:volume] == "N/A" || paper[:volume] == "0"%>
				  <%=", No.#{paper[:volumeno]}" unless paper[:volumeno].to_s.empty? || \
								 				  paper[:volumeno] == "N/A" || paper[:volumeno] == "0"%>
			      <%=", Pages #{paper[:beginpage]}" unless paper[:beginpage].to_s.empty? || paper[:beginpage] == "N/A" || paper[:beginpage] == "0"%>
				  <%="- #{paper[:endpage]}" unless paper[:endpage].to_s.empty? || \
			       paper[:endpage] =="N/A" || paper[:endpage] =="0"%>											  
                  <%=", #{paper[:remarks]}" unless paper[:remarks].to_s.empty? || \
                                                 paper[:remarks] == "N/A" || paper[:remarks] == "0"%>
                  <%=" (#{paper[:cate]})" unless paper[:cate].to_s.empty? || paper[:cate] == "N/A" || paper[:cate] == "0" %>
				  <%=", (#{paper[:subgroup]})" unless paper[:subgroup].to_s.empty? || \
								             paper[:subgroup] =="N/A" || paper[:subgroup].blank?%>	
                </li>
              <% end %>
            </ul>
          <% else %>
            <div><%= I18n.t "front_end.teacher.no_data" %></div>
          <% end %>
        </div>
      </div>
      <div class="tab-pane" id="teacher-conference">
        <%= render partial: "teacher_title_bar",
                   locals: { title_name: I18n.t("front_end.teacher.publication.conference") } %>
        <div class="items">
          <% if @conference_paper.present? %>
            <ul class="publications" >
              <% @conference_paper.each do |paper| %>
                <li>
                  <%="#{paper[:author]}" %>
                  <%=", #{paper[:year]}" unless paper[:year].to_s.empty? || paper[:year] == "N/A" %>
                  <%=", #{paper[:title]}" unless paper[:title].to_s.empty? || paper[:title] == "N/A" %>
                  <%=", #{paper[:conference]}" unless paper[:conference].to_s.empty? || \
                                                  paper[:conference] == "N/A"%>
                  <%=", #{paper[:date]}" unless paper[:date].to_s.empty? || \
                                                  paper[:date] == "N/A"%>
                  <%=", (#{paper[:location]})" unless paper[:location].to_s.empty? || \
                                                  paper[:location] == "N/A" %>
                  <%=", #{paper[:remarks]}" unless paper[:remarks].to_s.empty? || \
																        paper[:remarks] == "N/A" || paper[:remarks] == "0"%>
                </li>
              <% end %>
            </ul>
          <% else %>
            <div><%= I18n.t "front_end.teacher.no_data" %></div>
          <% end %>
        </div>
      </div>
      <div class="tab-pane" id="teacher-book">
        <%= render partial: "teacher_title_bar",
                   locals: { title_name: I18n.t("front_end.teacher.publication.book") } %>
        <div class="items">
          <% if @books.present? %>
            <ul class="publications">
              <% @books.each do |book| %>
                <li>
                  <%="#{book[:author]}" %>
                  <%=", #{book[:year]}" unless book[:year].to_s.empty? || book[:year] == "N/A" %>
                  <%=", #{book[:title]}" unless book[:title].to_s.empty? || book[:title] == "N/A" %>
                  <%=", #{book[:remarks]}" unless book[:remarks].to_s.empty? || \
                                                  book[:remarks] == "N/A"%>
                  <%=", #{book[:publisher]}" unless book[:publisher].to_s.empty? || \
                                                  book[:publisher] == "N/A"%>
                  <%=" (#{book[:book_title]})" unless book[:book_title].to_s.empty? || \
                                                  book[:book_title] == "N/A" %>
                </li>
              <% end %>
            </ul>
          <% else %>
            <div><%= I18n.t "front_end.teacher.no_data" %></div>
          <% end %>
        </div>
      </div>
      <div class="tab-pane" id="teacher-other">
          <%= render partial: "teacher_title_bar",
                     locals: { title_name: I18n.t("front_end.teacher.publication.other") } %>
          <div class="items">
            <% if !@use_ntu_data %>
              <div><%= I18n.t "front_end.teacher.no_data" %></div>
            <% elsif @other_publications.present? %>
              <ul class="publications">
                <% @other_publications.each do |book| %>
                  <li>
                    <%="#{book[:author]}" %>
                    <%=", #{book[:year]}" unless book[:year].to_s.empty? || book[:year] == "N/A" %>
                    <%=", #{book[:title]}" unless book[:title].to_s.empty? || book[:title] == "N/A" %>
                    <%=", #{book[:remarks]}" unless book[:remarks].to_s.empty? || \
                                                    book[:remarks] == "N/A"%>
                    <%=", #{book[:publisher]}" unless book[:publisher].to_s.empty? || \
                                                    book[:publisher] == "N/A"%>
                    <%=" (#{book[:book_title]})" unless book[:book_title].to_s.empty? || \
                                                    book[:book_title] == "N/A" %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/teachers/update.html.erb
<h1>Teachers#update</h1>
<p>Find me in app/views/teachers/update.html.erb</p>